version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: experiment-zookeeper
    ports:
      - "2181"
  kafka1:
    image: wurstmeister/kafka
    container_name: experiment-kafka1
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.31.134.22
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka
    container_name: experiment-kafka2
    depends_on:
      - zookeeper
    ports:
      - "9095:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.31.134.22
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql:5.6
    container_name: experiment-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_experiment
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:5.0.7
    container_name: experiment-redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
  experiment-api-server:
    container_name: experiment-api-server
    depends_on:
      - mysql
      - redis
      - zookeeper
      - kafka1
      - kafka2
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure